#!/bin/bash
# =============================================================================
# DADA2 Pipeline User-Facing Wrapper
# Installed to ~/bin by setup.sh — can be called from anywhere
# Reads configuration from config.sh and submits SLURM job
# =============================================================================

set -euo pipefail

print_help() {
cat << 'HELP'
run_dada2processing — Submit the DADA2 processing pipeline as a SLURM job

USAGE:
  run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [OPTIONS]

REQUIRED ARGUMENTS:
  input_fastq_dir     Path to directory containing raw fastq.gz files
  output_dir          Path to project output folder (will be created if needed)
  marker_gene         Sequencing target — one of:
                        16S-V4      bacterial 16S V4 region
                        ITS1        fungal ITS1 region
                        ITS2        fungal ITS2 region
                        18S-V4      microeukaryote 18S V4 region (protists)
                        18S-AMF     arbuscular mycorrhizal fungi 18S
  platform            Sequencing platform — one of:
                        illumina    Illumina MiSeq/NovaSeq
                        aviti       Aviti (Element Biosciences)

OPTIONS:
  --quality <good|bad>  Quality filtering stringency (default: good)
                        good: maxEE=c(2,2), stricter
                        bad:  maxEE=c(4,6), more permissive
  -h, --help            Show this help message and exit

EXAMPLES:
  run_dada2processing /path/to/fastq /path/to/output 16S-V4 illumina
  run_dada2processing /path/to/fastq /path/to/output ITS2 aviti --quality good
  run_dada2processing /path/to/fastq /path/to/output 18S-V4 illumina --quality bad

NOTES:
  - SLURM notifications are sent to the email address set during setup.sh
  - Output files are written to the output_dir
  - The primary output is a DADA2 abundance table with taxonomy assignments
  - Check the log files in output_dir for progress and diagnostics

HELP
}

# Find the pipeline directory (where this script is located)
# The script is copied to ~/bin, but we need to find the original repo location
# We store this in config.sh which was generated by setup.sh

# Look for config.sh in common locations
CONFIG=""
if [ -f "$HOME/.dada2_pipeline_config.sh" ]; then
  CONFIG="$HOME/.dada2_pipeline_config.sh"
elif [ -f "${BASH_SOURCE[0]%/*}/../config.sh" ]; then
  CONFIG="${BASH_SOURCE[0]%/*}/../config.sh"
else
  echo "ERROR: config.sh not found."
  echo "Please run setup.sh in the HTS_DADA2processing directory."
  exit 1
fi

source "$CONFIG"
[ -n "${PIPELINE_DIR:-}" ] || { echo "ERROR: PIPELINE_DIR not set in config.sh"; exit 1; }
[ -n "${SLURM_EMAIL:-}" ] || { echo "ERROR: SLURM_EMAIL not set in config.sh"; exit 1; }

# Parse arguments
QUALITY="good"

# Print help if no args or -h/--help
if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  print_help
  exit 0
fi

if [ $# -lt 4 ]; then
  echo "ERROR: Missing required arguments"
  echo "Usage: run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [--quality bad]"
  exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"
MARKER_GENE="$3"
PLATFORM="$4"
shift 4

# Parse optional arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --quality)
      if [ $# -lt 2 ]; then
        echo "ERROR: --quality requires an argument (good or bad)"
        exit 1
      fi
      QUALITY="$2"
      shift 2
      ;;
    *)
      echo "ERROR: Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate arguments
if [ ! -d "$INPUT_DIR" ]; then
  echo "ERROR: Input directory not found: $INPUT_DIR"
  exit 1
fi

if ! ls "$INPUT_DIR"/*_R1_*.fastq.gz > /dev/null 2>&1 && ! ls "$INPUT_DIR"/*_R1.fastq.gz > /dev/null 2>&1; then
  echo "ERROR: No fastq.gz files found in $INPUT_DIR"
  exit 1
fi

if ! [[ "$MARKER_GENE" =~ ^(16S-V4|ITS1|ITS2|18S-V4|18S-AMF)$ ]]; then
  echo "ERROR: Invalid marker_gene: $MARKER_GENE"
  echo "Valid options: 16S-V4, ITS1, ITS2, 18S-V4, 18S-AMF"
  exit 1
fi

if ! [[ "$PLATFORM" =~ ^(illumina|aviti)$ ]]; then
  echo "ERROR: Invalid platform: $PLATFORM"
  echo "Valid options: illumina, aviti"
  exit 1
fi

if ! [[ "$QUALITY" =~ ^(good|bad)$ ]]; then
  echo "ERROR: Invalid quality: $QUALITY"
  echo "Valid options: good, bad"
  exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo ""
echo "============================================================"
echo "  DADA2 Processing Pipeline"
echo "============================================================"
echo "  Input directory:  $INPUT_DIR"
echo "  Output directory: $OUTPUT_DIR"
echo "  Marker gene:      $MARKER_GENE"
echo "  Platform:         $PLATFORM"
echo "  Quality:          $QUALITY"
echo "============================================================"
echo ""

# Submit the SLURM job
echo "Submitting SLURM job..."
sbatch \
  --mail-user="$SLURM_EMAIL" \
  --output="$OUTPUT_DIR/pipeline_%j.out" \
  --error="$OUTPUT_DIR/pipeline_%j.err" \
  --export=ALL,PIPELINE_DIR="$PIPELINE_DIR" \
  "$PIPELINE_DIR/dada2processing_msiSLURM.sh" \
  "$INPUT_DIR" \
  "$OUTPUT_DIR" \
  "$MARKER_GENE" \
  "$PLATFORM" \
  "$QUALITY"

echo ""
echo "Job submitted! Check your email for status updates."
echo "Monitor progress with: tail -f $OUTPUT_DIR/pipeline_*.out"
echo ""
