#!/bin/bash
# =============================================================================
# DADA2 Processing Pipeline Setup Script
# Run once after cloning to configure the pipeline for your account
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "============================================================"
echo "  DADA2 Processing Pipeline Setup"
echo "============================================================"
echo "  Repository directory: $REPO_DIR"
echo ""

# ------------------------------------------------------------------------------
# 1. Generate config.sh
# ------------------------------------------------------------------------------

echo "--- Generating config.sh ---"

read -p "  Enter your email address for SLURM notifications: " USER_EMAIL

cat > "$REPO_DIR/config.sh" << EOF
#!/bin/bash
# Auto-generated by setup.sh — do not commit this file
# Re-run setup.sh to regenerate, or edit manually

PIPELINE_DIR="$REPO_DIR"
SLURM_EMAIL="$USER_EMAIL"
EOF

chmod 600 "$REPO_DIR/config.sh"
echo "  config.sh written."

# ------------------------------------------------------------------------------
# 2. Install run_dada2processing command
# ------------------------------------------------------------------------------

echo ""
echo "--- Installing run_dada2processing command ---"

mkdir -p "$HOME/bin"

# Copy (not symlink) the wrapper script to ~/bin so it works from anywhere
cp "$REPO_DIR/run_dada2processing.sh" "$HOME/bin/run_dada2processing"
chmod +x "$HOME/bin/run_dada2processing"

echo "  Installed run_dada2processing to $HOME/bin"
echo "  Make sure $HOME/bin is in your PATH:"
echo "    echo 'export PATH=\$HOME/bin:\$PATH' >> ~/.bashrc"
echo "    source ~/.bashrc"

# ------------------------------------------------------------------------------
# 3. Verify R and required packages
# ------------------------------------------------------------------------------

echo ""
echo "--- Verifying R environment ---"

if ! command -v Rscript &> /dev/null; then
  echo "  WARNING: Rscript not found. You may need to load R module on MSI:"
  echo "    module load R/4.4.0-openblas-rocky8"
else
  echo "  R is available: $(Rscript --version 2>&1 | head -1)"
fi

# Check for dada2 package (but don't fail if it's not installed yet — users might install it via conda)
echo "  Note: dada2 and other R packages will be loaded via module on MSI at runtime"

# ------------------------------------------------------------------------------
# 4. Check for Aviti adapter files
# ------------------------------------------------------------------------------

echo ""
echo "--- Checking for Aviti adapter FASTA files ---"

AVITI_ADAPTER="$REPO_DIR/scripts/aviti/aviti_adapters.fa"
AVITI_PRIMER="$REPO_DIR/scripts/aviti/aviti_ITSprimer_as_adapter.fa"

if [ ! -f "$AVITI_ADAPTER" ]; then
  echo "  WARNING: $AVITI_ADAPTER not found"
  echo "  This file is needed for Aviti adapter trimming."
  echo "  Please request from Trevor Gould and place it in scripts/aviti/"
fi

if [ ! -f "$AVITI_PRIMER" ]; then
  echo "  WARNING: $AVITI_PRIMER not found"
  echo "  This file is needed for Aviti adapter trimming."
  echo "  Please request from Trevor Gould and place it in scripts/aviti/"
fi

# ------------------------------------------------------------------------------
# 5. Final summary
# ------------------------------------------------------------------------------

echo ""
echo "============================================================"
echo "  Setup complete!"
echo "============================================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. Update your PATH to include ~/bin (if not already done):"
echo "     echo 'export PATH=\$HOME/bin:\$PATH' >> ~/.bashrc"
echo "     source ~/.bashrc"
echo ""
echo "  2. Test the installation:"
echo "     run_dada2processing --help"
echo ""
echo "  3. Run the pipeline:"
echo "     run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [--quality bad]"
echo ""
echo "  Examples:"
echo "     run_dada2processing /path/to/fastq /path/to/output 16S-V4 illumina"
echo "     run_dada2processing /path/to/fastq /path/to/output ITS2 aviti --quality good"
echo ""
