#!/bin/bash
# =============================================================================
# DADA2 Processing Pipeline Setup Script
# Run once after cloning to configure the pipeline for your account
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "============================================================"
echo "  DADA2 Processing Pipeline Setup"
echo "============================================================"
echo "  Repository directory: $REPO_DIR"
echo ""

# ------------------------------------------------------------------------------
# 1. Generate config.sh
# ------------------------------------------------------------------------------

echo "--- Generating config.sh ---"

read -p "  Enter your email address for SLURM notifications: " USER_EMAIL

cat > "$REPO_DIR/config.sh" << EOF
#!/bin/bash
# Auto-generated by setup.sh — do not commit this file
# Re-run setup.sh to regenerate, or edit manually

PIPELINE_DIR="$REPO_DIR"
SLURM_EMAIL="$USER_EMAIL"
EOF

chmod 600 "$REPO_DIR/config.sh"
echo "  config.sh written."

# ------------------------------------------------------------------------------
# 2. Install run_dada2processing command
# ------------------------------------------------------------------------------

echo ""
echo "--- Installing run_dada2processing command ---"

mkdir -p "$HOME/bin"

# Create the wrapper script with the PIPELINE_DIR path embedded
cat > "$HOME/bin/run_dada2processing" << 'WRAPPER_SCRIPT'
#!/bin/bash
# DADA2 Pipeline User-Facing Wrapper
# Auto-installed by setup.sh with PIPELINE_DIR embedded

PIPELINE_DIR="PIPELINE_DIR_PLACEHOLDER"

set -euo pipefail

print_help() {
cat << 'HELP'
run_dada2processing — Submit the DADA2 processing pipeline as a SLURM job

USAGE:
  run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [OPTIONS]

REQUIRED ARGUMENTS:
  input_fastq_dir     Path to directory containing raw fastq.gz files
  output_dir          Path to project output folder (will be created if needed)
  marker_gene         Sequencing target — one of:
                        16S-V4      bacterial 16S V4 region
                        ITS1        fungal ITS1 region
                        ITS2        fungal ITS2 region
                        18S-V4      microeukaryote 18S V4 region (protists)
                        18S-AMF     arbuscular mycorrhizal fungi 18S
  platform            Sequencing platform — one of:
                        illumina    Illumina MiSeq/NovaSeq
                        aviti       Aviti (Element Biosciences)

OPTIONS:
  --quality <good|bad>  Quality filtering stringency (default: good)
                        good: maxEE=c(2,2), stricter
                        bad:  maxEE=c(4,6), more permissive
  -h, --help            Show this help message and exit

EXAMPLES:
  run_dada2processing /path/to/fastq /path/to/output 16S-V4 illumina
  run_dada2processing /path/to/fastq /path/to/output ITS2 aviti --quality good

HELP
}

CONFIG="$PIPELINE_DIR/config.sh"
[ -f "$CONFIG" ] || {
  echo "ERROR: config.sh not found at $CONFIG"
  echo "Please re-run setup.sh in the HTS_DADA2processing directory."
  exit 1
}

source "$CONFIG"
[ -n "${PIPELINE_DIR:-}" ] || { echo "ERROR: PIPELINE_DIR not set in config.sh"; exit 1; }
[ -n "${SLURM_EMAIL:-}" ] || { echo "ERROR: SLURM_EMAIL not set in config.sh"; exit 1; }

QUALITY="good"

if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  print_help
  exit 0
fi

if [ $# -lt 4 ]; then
  echo "ERROR: Missing required arguments"
  echo "Usage: run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [--quality bad]"
  exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"
MARKER_GENE="$3"
PLATFORM="$4"
shift 4

while [ $# -gt 0 ]; do
  case "$1" in
    --quality)
      [ $# -lt 2 ] && { echo "ERROR: --quality requires an argument (good or bad)"; exit 1; }
      QUALITY="$2"
      shift 2
      ;;
    *)
      echo "ERROR: Unknown option: $1"
      exit 1
      ;;
  esac
done

[ -d "$INPUT_DIR" ] || { echo "ERROR: Input directory not found: $INPUT_DIR"; exit 1; }
ls "$INPUT_DIR"/*_R1_*.fastq.gz > /dev/null 2>&1 || ls "$INPUT_DIR"/*_R1.fastq.gz > /dev/null 2>&1 || { echo "ERROR: No fastq.gz files found in $INPUT_DIR"; exit 1; }

[[ "$MARKER_GENE" =~ ^(16S-V4|ITS1|ITS2|18S-V4|18S-AMF)$ ]] || { echo "ERROR: Invalid marker_gene: $MARKER_GENE"; exit 1; }
[[ "$PLATFORM" =~ ^(illumina|aviti)$ ]] || { echo "ERROR: Invalid platform: $PLATFORM"; exit 1; }
[[ "$QUALITY" =~ ^(good|bad)$ ]] || { echo "ERROR: Invalid quality: $QUALITY"; exit 1; }

mkdir -p "$OUTPUT_DIR"

echo ""
echo "============================================================"
echo "  DADA2 Processing Pipeline"
echo "============================================================"
echo "  Input directory:  $INPUT_DIR"
echo "  Output directory: $OUTPUT_DIR"
echo "  Marker gene:      $MARKER_GENE"
echo "  Platform:         $PLATFORM"
echo "  Quality:          $QUALITY"
echo "============================================================"
echo ""

echo "Submitting SLURM job..."
sbatch \
  --mail-user="$SLURM_EMAIL" \
  --output="$OUTPUT_DIR/pipeline_%j.out" \
  --error="$OUTPUT_DIR/pipeline_%j.err" \
  --export=ALL,PIPELINE_DIR="$PIPELINE_DIR" \
  "$PIPELINE_DIR/dada2processing_msiSLURM.sh" \
  "$INPUT_DIR" \
  "$OUTPUT_DIR" \
  "$MARKER_GENE" \
  "$PLATFORM" \
  "$QUALITY"

echo ""
echo "Job submitted! Check your email for status updates."
echo "Monitor progress with: tail -f $OUTPUT_DIR/pipeline_*.out"
echo ""
WRAPPER_SCRIPT

# Replace the placeholder with the actual PIPELINE_DIR
# Use sed with proper escaping of the path
sed -i.bak "s|PIPELINE_DIR_PLACEHOLDER|$(printf '%s\n' "$REPO_DIR" | sed -e 's/[\/&]/\\&/g')|g" "$HOME/bin/run_dada2processing"
rm -f "$HOME/bin/run_dada2processing.bak"
chmod +x "$HOME/bin/run_dada2processing"

echo "  Installed run_dada2processing to $HOME/bin"
echo "  Make sure $HOME/bin is in your PATH:"
echo "    echo 'export PATH=\$HOME/bin:\$PATH' >> ~/.bashrc"
echo "    source ~/.bashrc"

# ------------------------------------------------------------------------------
# 3. Create conda environment with DADA2 and dependencies
# ------------------------------------------------------------------------------

echo ""
echo "--- Checking for required modules and R packages ---"

# Check if we're on MSI (where module command is available)
# Initialize modules if not already loaded
if ! command -v module &> /dev/null; then
  if [ -f /usr/share/Modules/init/bash ]; then
    source /usr/share/Modules/init/bash
  fi
fi

if command -v module &> /dev/null; then
  # Load R module and check for dada2
  module load R/4.4.2-openblas-rocky8

  echo "  Checking if dada2 is installed in R/4.4.0..."
  if Rscript -e "library(dada2)" 2>/dev/null; then
    echo "  ✓ dada2 is installed"
  else
    echo "  dada2 not found, installing from Bioconductor..."
    Rscript << 'RINSTALL'
if (!require("dada2", quietly = TRUE)) {
  if (!require("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager", repos = "http://cran.us.r-project.org")
  }
  BiocManager::install("dada2")
}
library(dada2)
cat("✓ dada2 installed successfully\n")
RINSTALL
    if [ $? -ne 0 ]; then
      echo "  WARNING: Failed to install dada2. You may need to install it manually on MSI:"
      echo "    Rscript << 'EOF'"
      echo "    if (!require('BiocManager', quietly = TRUE))"
      echo "      install.packages('BiocManager')"
      echo "    BiocManager::install('dada2')"
      echo "    EOF"
    fi
  fi

  echo ""
  echo "  Required modules for the pipeline:"
  echo "    - R/4.4.2-openblas-rocky8 (for DADA2 processing) ✓"
  echo "    - cutadapt (for adapter trimming)"
  echo "    - trimmomatic (for Aviti adapter trimming)"
else
  echo "  (Not on MSI — module system not available)"
  echo ""
  echo "  When you run on MSI, these modules will be loaded automatically:"
  echo "    - R/4.4.2-openblas-rocky8 (with dada2 package installed)"
  echo "    - cutadapt (for adapter trimming)"
  echo "    - trimmomatic (for Aviti adapter trimming)"
fi

echo ""
echo "  If you encounter module loading errors, manually load them:"
echo "    module load R/4.4.2-openblas-rocky8 cutadapt trimmomatic"
echo ""
echo "  ✓ Module-based dependency approach ready"

# ------------------------------------------------------------------------------
# 4. Check for Aviti adapter files
# ------------------------------------------------------------------------------

echo ""
echo "--- Checking for Aviti adapter FASTA files ---"

AVITI_ADAPTER="$REPO_DIR/scripts/aviti/aviti_adapters.fa"
AVITI_PRIMER="$REPO_DIR/scripts/aviti/aviti_ITSprimer_as_adapter.fa"

if [ ! -f "$AVITI_ADAPTER" ]; then
  echo "  WARNING: $AVITI_ADAPTER not found"
  echo "  This file is needed for Aviti adapter trimming."
  echo "  Please request from Trevor Gould and place it in scripts/aviti/"
fi

if [ ! -f "$AVITI_PRIMER" ]; then
  echo "  WARNING: $AVITI_PRIMER not found"
  echo "  This file is needed for Aviti adapter trimming."
  echo "  Please request from Trevor Gould and place it in scripts/aviti/"
fi

# ------------------------------------------------------------------------------
# 5. Final summary
# ------------------------------------------------------------------------------

echo ""
echo "============================================================"
echo "  Setup complete!"
echo "============================================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. Update your PATH to include ~/bin (if not already done):"
echo "     echo 'export PATH=\$HOME/bin:\$PATH' >> ~/.bashrc"
echo "     source ~/.bashrc"
echo ""
echo "  2. Test the installation:"
echo "     run_dada2processing --help"
echo ""
echo "  3. Run the pipeline:"
echo "     run_dada2processing <input_fastq_dir> <output_dir> <marker_gene> <platform> [--quality bad]"
echo ""
echo "  Examples:"
echo "     run_dada2processing /path/to/fastq /path/to/output 16S-V4 illumina"
echo "     run_dada2processing /path/to/fastq /path/to/output ITS2 aviti --quality good"
echo ""
